package com.qsim.view;

import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aleja
 */
public class DetalleSimulacion extends javax.swing.JPanel {

    /**
     * Creates new form DetalleHora
     */
    public DetalleSimulacion() {
        initComponents();
    }

    public void setModel(DefaultTableModel model) {
        JTable tabla = new JTable(model);
        
        JScrollPane panel = new JScrollPane(tabla);

        tablePanel.removeAll();
        tablePanel.add(panel);
        tablePanel.repaint();

        System.out.println("Prueba");
        System.out.println("Columnas: " + tabla.getColumnCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(410, 470));
        setLayout(null);
        add(tablePanel);
        tablePanel.setBounds(20, 40, 370, 350);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables
}
