package com.qsim.view;

import com.qsim.main.QSim;
import com.qsim.model.NumericFieldParser;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

public class FormPrincipal extends javax.swing.JPanel {

    private int serviceMean;

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customersField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serviceField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productsField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hoursField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(363, 234));
        setLayout(null);
        add(customersField);
        customersField.setBounds(16, 63, 79, 27);

        jLabel1.setText("Media de clientes por hora:");
        add(jLabel1);
        jLabel1.setBounds(16, 42, 161, 21);

        jLabel2.setText("Tiempo medio de servicio:");
        add(jLabel2);
        jLabel2.setBounds(193, 42, 154, 21);
        add(serviceField);
        serviceField.setBounds(193, 63, 79, 27);

        jLabel3.setText("Media de productos:");
        add(jLabel3);
        jLabel3.setBounds(16, 106, 121, 21);
        add(productsField);
        productsField.setBounds(16, 127, 79, 27);

        jLabel4.setText("Horas por simular:");
        add(jLabel4);
        jLabel4.setBounds(193, 106, 107, 21);
        add(hoursField);
        hoursField.setBounds(193, 127, 79, 27);

        calculateButton.setText("Calcular");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        add(calculateButton);
        calculateButton.setBounds(145, 170, 73, 27);
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        NumericFieldParser parser = createNumericFieldParser();
        DefaultTableModel model = createTableModel(parser);
        changePanel(model);
    }//GEN-LAST:event_calculateButtonActionPerformed

    private NumericFieldParser createNumericFieldParser() {
        NumericFieldParser parser = new NumericFieldParser();
        parser.getNumbersFromTextFields(customersField, serviceField, productsField, hoursField);
        return parser;
    }

    private DefaultTableModel createTableModel(NumericFieldParser parser) {
        DefaultTableModel model = new DefaultTableModel();
        addColumnsToTableModel(model);
        addRowsToTableModel(model, parser);
        return model;
    }

    private void addColumnsToTableModel(DefaultTableModel model) {
        model.addColumn("Hora");
        model.addColumn("λ");
        model.addColumn("μ");
        model.addColumn("Total Clientes");
    }

    private void addRowsToTableModel(DefaultTableModel model, NumericFieldParser parser) {
        serviceMean = parser.getNumberOf(serviceField);
        for (int hour = 1; hour <= parser.getNumberOf(hoursField); hour++) {
            model.addRow(
                    new Object[]{
                        hour,
                        getLambdaFromGaussDistribution(parser.getNumberOf(customersField)),
                        serviceMean,
                        "Prueba"});
        }
    }

    private int getLambdaFromGaussDistribution(int mean) {
        Random random = new Random();
        double standardDeviation = Math.sqrt(mean);
        int randomValue = (int) Math.round(random.nextGaussian() * standardDeviation + mean);
        if (randomValue <= 0) {
            randomValue = 1;
        } else if (randomValue >= serviceMean) {
            randomValue = serviceMean - 1;
        }
        return randomValue;
    }

    private void changePanel(DefaultTableModel model) {
        QSim.frame.setContentPane(new DetalleSimulacion(model));
        QSim.frame.pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField customersField;
    private javax.swing.JTextField hoursField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField productsField;
    private javax.swing.JTextField serviceField;
    // End of variables declaration//GEN-END:variables
}
