/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qsim.view;

/**
 *
 * @author aleja
 */
public class GastoForm extends javax.swing.JPanel {

    /**
     * Creates new form DetalleGasto
     */
    public GastoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        gastoTextField = new javax.swing.JTextField();
        cancelarButton = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Id:");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 60, 20);
        add(idTextField);
        idTextField.setBounds(90, 20, 100, 20);

        guardarButton.setText("Guardar");
        add(guardarButton);
        guardarButton.setBounds(110, 110, 80, 20);

        jLabel2.setText("Nombre:");
        add(jLabel2);
        jLabel2.setBounds(20, 50, 60, 20);
        add(nombreTextField);
        nombreTextField.setBounds(90, 50, 100, 20);

        jLabel3.setText("Gasto:");
        add(jLabel3);
        jLabel3.setBounds(20, 80, 60, 20);
        add(gastoTextField);
        gastoTextField.setBounds(90, 80, 100, 20);

        cancelarButton.setText("Cancelar");
        add(cancelarButton);
        cancelarButton.setBounds(20, 110, 80, 20);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField gastoTextField;
    private javax.swing.JButton guardarButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombreTextField;
    // End of variables declaration//GEN-END:variables
}
