package com.qsim.view;

import com.qsim.main.QSim;
import com.qsim.model.NumericFieldParser;
import com.qsim.model.Producto;

/**
 *
 * @author aleja
 */
public class InventarioForm extends javax.swing.JPanel {

    Producto producto;
    
    /**
     * Creates new form DetalleGasto
     */
    public InventarioForm() {
        initComponents();
        setSize(getPreferredSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        precioCompraTextField = new javax.swing.JTextField();
        precioVentaTextField = new javax.swing.JTextField();
        cancelarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(260, 180));
        setLayout(null);

        jLabel1.setText("Id:");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 60, 20);
        add(idTextField);
        idTextField.setBounds(140, 20, 100, 20);

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        add(guardarButton);
        guardarButton.setBounds(160, 140, 80, 20);

        jLabel2.setText("Nombre:");
        add(jLabel2);
        jLabel2.setBounds(20, 50, 60, 20);
        add(precioCompraTextField);
        precioCompraTextField.setBounds(140, 80, 100, 20);
        add(precioVentaTextField);
        precioVentaTextField.setBounds(140, 110, 100, 20);

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        add(cancelarButton);
        cancelarButton.setBounds(20, 140, 80, 20);

        jLabel4.setText("Precio de Compra:");
        add(jLabel4);
        jLabel4.setBounds(20, 80, 120, 20);
        add(nombreTextField);
        nombreTextField.setBounds(140, 50, 100, 20);

        jLabel5.setText("Precio de Venta:");
        add(jLabel5);
        jLabel5.setBounds(20, 110, 120, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        producto = null;
        
        FormPrincipal panel = new FormPrincipal();

        QSim.frame.setContentPane(panel);
        QSim.frame.pack();
        QSim.frame.setLocationRelativeTo(null);

        panel.reemplazarPanel(new InventarioPanel());
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
        NumericFieldParser parser = new NumericFieldParser();
        parser.parseNumbersFromTextFields(idTextField, precioCompraTextField, precioVentaTextField);
        comprobarId(parser.getIntegerFrom(idTextField));
        comprobarNombre();
        comprobarPrecioCompra(parser.getDoubleFrom(precioCompraTextField));
        comprobarPrecioVenta(parser.getDoubleFrom(precioVentaTextField));
    }//GEN-LAST:event_guardarButtonActionPerformed
    
    private void comprobarId(int id) throws IllegalArgumentException {
        if (id < 0)
    }
    
    private void comprobarNombre() {
        
    }
    
    private void comprobarPrecioCompra() {
        
    }
    
    private void comprobarPrecioVenta() {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField precioCompraTextField;
    private javax.swing.JTextField precioVentaTextField;
    // End of variables declaration//GEN-END:variables
}
