package com.qsim.view;

import com.qsim.main.QSim;
import com.qsim.model.Producto;
import com.qsim.util.TableFactory;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JScrollPane;

/**
 *
 * @author aleja
 */
public class InventarioPanel extends javax.swing.JPanel {

    private List<Producto> inventario;
    private InventarioForm formulario;

    /**
     * Creates new form GastosPanel
     */
    public InventarioPanel() {
        initComponents();
        setSize(getPreferredSize());
        recuperarRegistros("inventario.bin");
        mostrarRegistros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        nuevoButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(550, 570));
        setLayout(null);

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLabel.setText("Inventario");
        add(tituloLabel);
        tituloLabel.setBounds(20, 20, 240, 30);

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        add(mainPanel);
        mainPanel.setBounds(20, 50, 400, 500);

        nuevoButton.setText("Nuevo");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });
        add(nuevoButton);
        nuevoButton.setBounds(430, 50, 100, 30);

        eliminarButton.setText("Eliminar");
        add(eliminarButton);
        eliminarButton.setBounds(430, 130, 100, 30);

        editarButton.setText("Editar");
        add(editarButton);
        editarButton.setBounds(430, 90, 100, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed
        formulario = new InventarioForm();
        
        QSim.frame.setContentPane(formulario);
        QSim.frame.pack();
        QSim.frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_nuevoButtonActionPerformed

    private void recuperarRegistros(String ruta) {
        try (ObjectInputStream objectInputStream = new ObjectInputStream(new FileInputStream(ruta))) {
            inventario = (List<Producto>) objectInputStream.readObject();
        } catch (IOException | ClassNotFoundException e) {
            inventarioPredeterminado();
        }
    }

    private boolean guardarRegistros(String ruta) {
        try (ObjectOutputStream objectOutputStream = new ObjectOutputStream(new FileOutputStream(ruta))) {
            objectOutputStream.writeObject(inventario);
            return true;
        } catch (IOException e) {
            return false;
        }
    }

    private void mostrarRegistros() {
        JScrollPane panel = new JScrollPane(TableFactory.crearProductoTable(inventario));
        panel.setSize(mainPanel.getSize());

        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.repaint();
    }

    private void inventarioPredeterminado() {
        inventario = new ArrayList<>();

        inventario.add(new Producto(1, "Paracetamol", 5.0, 10.0));
        inventario.add(new Producto(2, "Ibuprofeno", 6.0, 12.0));
        inventario.add(new Producto(3, "Vitamina C", 3.0, 7.0));
        inventario.add(new Producto(4, "Analgésico", 4.0, 8.0));
        inventario.add(new Producto(5, "Antibiótico", 10.0, 20.0));
        inventario.add(new Producto(6, "Antiinflamatorio", 7.0, 15.0));
        inventario.add(new Producto(7, "Jarabe para la tos", 8.0, 16.0));
        inventario.add(new Producto(8, "Pastillas para la gripe", 9.0, 18.0));
        inventario.add(new Producto(9, "Colirio", 6.0, 12.0));
        inventario.add(new Producto(10, "Antiséptico", 5.0, 11.0));
        inventario.add(new Producto(11, "Crema antiarrugas", 15.0, 30.0));
        inventario.add(new Producto(12, "Protector solar", 12.0, 25.0));
        inventario.add(new Producto(13, "Loción hidratante", 8.0, 18.0));
        inventario.add(new Producto(14, "Shampoo anticaspa", 7.0, 14.0));
        inventario.add(new Producto(15, "Desodorante", 4.0, 9.0));
        inventario.add(new Producto(16, "Cepillo dental", 2.0, 5.0));
        inventario.add(new Producto(17, "Pasta dental", 3.0, 6.0));
        inventario.add(new Producto(18, "Enjuague bucal", 4.0, 8.0));
        inventario.add(new Producto(19, "Gasas estériles", 6.0, 12.0));
        inventario.add(new Producto(20, "Vendas elásticas", 7.0, 15.0));
        inventario.add(new Producto(21, "Algodón", 3.0, 7.0));
        inventario.add(new Producto(22, "Termómetro digital", 10.0, 20.0));
        inventario.add(new Producto(23, "Tijeras quirúrgicas", 15.0, 30.0));
        inventario.add(new Producto(24, "Guantes desechables", 8.0, 16.0));
        inventario.add(new Producto(25, "Mascarillas", 5.0, 11.0));
        inventario.add(new Producto(26, "Jeringas", 7.0, 15.0));
        inventario.add(new Producto(27, "Alcohol en gel", 6.0, 13.0));
        inventario.add(new Producto(28, "Pomada cicatrizante", 9.0, 19.0));
        inventario.add(new Producto(29, "Suplemento vitamínico", 12.0, 25.0));
        inventario.add(new Producto(30, "Gotas oftálmicas", 8.0, 17.0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
