package com.qsim.view;

/**
 *
 * @author aleja
 */
public class SimulacionPanel extends javax.swing.JPanel {

    /**
     * Creates new form SimulacionPanel
     */
    public SimulacionPanel() {
        initComponents();
        setSize(getPreferredSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customersField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serviceField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productsField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hoursField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(330, 230));
        setLayout(null);
        add(customersField);
        customersField.setBounds(210, 20, 100, 30);

        jLabel1.setText("Media de clientes por hora:");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 160, 30);

        jLabel2.setText("Tiempo medio de servicio:");
        add(jLabel2);
        jLabel2.setBounds(20, 60, 160, 30);
        add(serviceField);
        serviceField.setBounds(210, 60, 100, 30);

        jLabel3.setText("Media de productos:");
        add(jLabel3);
        jLabel3.setBounds(20, 140, 160, 30);
        add(productsField);
        productsField.setBounds(210, 140, 100, 30);

        jLabel4.setText("Horas por simular:");
        add(jLabel4);
        jLabel4.setBounds(20, 100, 160, 30);
        add(hoursField);
        hoursField.setBounds(210, 100, 100, 30);

        calculateButton.setText("Calcular");
        add(calculateButton);
        calculateButton.setBounds(210, 180, 100, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField customersField;
    private javax.swing.JTextField hoursField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField productsField;
    private javax.swing.JTextField serviceField;
    // End of variables declaration//GEN-END:variables
}
