package com.qsim.view;

/**
 *
 * @author aleja
 */
public class SimulacionPanel extends javax.swing.JPanel {

    /**
     * Creates new form SimulacionPanel
     */
    public SimulacionPanel() {
        initComponents();
        setSize(getPreferredSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mediaClientesText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mediaServicioTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mediaProductosTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        horasPorSimularTextField = new javax.swing.JTextField();
        calcularButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(330, 230));
        setLayout(null);
        add(mediaClientesText);
        mediaClientesText.setBounds(210, 20, 100, 30);

        jLabel1.setText("Media de clientes por hora:");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 160, 30);

        jLabel2.setText("Tiempo medio de servicio:");
        add(jLabel2);
        jLabel2.setBounds(20, 60, 160, 30);
        add(mediaServicioTextField);
        mediaServicioTextField.setBounds(210, 60, 100, 30);

        jLabel3.setText("Media de productos:");
        add(jLabel3);
        jLabel3.setBounds(20, 140, 160, 30);
        add(mediaProductosTextField);
        mediaProductosTextField.setBounds(210, 140, 100, 30);

        jLabel4.setText("Horas por simular:");
        add(jLabel4);
        jLabel4.setBounds(20, 100, 160, 30);
        add(horasPorSimularTextField);
        horasPorSimularTextField.setBounds(210, 100, 100, 30);

        calcularButton.setText("Calcular");
        calcularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularButtonActionPerformed(evt);
            }
        });
        add(calcularButton);
        calcularButton.setBounds(210, 180, 100, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_calcularButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularButton;
    private javax.swing.JTextField horasPorSimularTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mediaClientesText;
    private javax.swing.JTextField mediaProductosTextField;
    private javax.swing.JTextField mediaServicioTextField;
    // End of variables declaration//GEN-END:variables
}
